### ISSUE TITLE
Support API v2.1

### ISSUE THREAD

**Issue by sbaechler** [feinheit/django-facebook-graph#26]
Support the new Facebook API.

**Comment by sbaechler** [comment]
Started work: https://github.com/sbaechler/django-facebook-graph/tree/versions

**Comment by Tom-Potanski** [comment]
Does it currently supports API v2.0?

**Comment by sbaechler** [comment]
Not yet. We are updating our apps next month, during which I plan to update the Graph API. Since we only have one app left that is actually deeply integrated with Facebook,  I think that I will just update the modules I'm actually using.
So if you are creating a new project, I suggest you use a different Facebook library for now.

**Comment by Allan-Nava** [comment]
Is still live this project?

**Comment by matthiask** [comment]
It's not actively maintained, and probably does not work anymore with current versions of the Facebook Graph API.

**Comment by Allan-Nava** [comment]
Do you know @matthiask any library for facebook api ?

**Comment by matthiask** [comment]
Unfortunately I do not, besides maybe the official Python SDK (http://facebook-sdk.readthedocs.io/en/latest/index.html)

That being said, I mostly use direct access to the Graph APIs (using http://docs.python-requests.org/en/master/) these days for the very limited Facebook API access that I have to concern myself with :)
