### ISSUE TITLE
Flush Django Session

### ISSUE THREAD

**Issue by schmidsi** [feinheit/django-facebook-graph#6]
not 100% sure, but facebook.backends.registration.views.logout should also flush the django session:

request.session.flush()

maybe its already done by line #85: response = auth_views.logout(request, next_page, template_name, redirect_field_name)

**Comment by sbaechler** [comment]
auth.logout flushes the session.
But we should fix the deauthorization callback so it deletes the User and their data. Maybe there is a possibility to delete a user's session on a Facebook deauthorization callback.

**Comment by sbaechler** [comment]
Session data is encoded (SessionStore backend) so we cannot easily delete a user session.
Deauthorize callback is fixed.
